name: Benchmark Main

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test

    # Run benchmarks
    - name: Run Benchmarks
      run: dotnet run -c Release --project ContactBook.Benchmark --filter ContactBook.Benchmark.Features* --artifacts BenchmarkDotNet.Artifacts.Main
      
    # Upload the Results: https://github.com/marketplace/actions/upload-a-build-artifact
    - name: Upload benchmark artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Benchmark Artifacts Main
        path: BenchmarkDotNet.Artifacts.Main