name: .NET Core Perf Regression

on:
  pull_request:
    branches: [ "main" ]

jobs:
  benchmark:
    runs-on: ubuntu-latest  # For a list of available runner types, refer to
    # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      # Install the .NET Core workload
      - name: Install .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      
      # Run benchmarks
      - name: Run Benchmarks on Current Branch
        run: dotnet run -c Release --project ContactBook.Benchmark --filter ContactBook.Benchmark.Features* --artifacts BenchmarkDotNet.Artifacts.Current
      
      # Upload the Results: https://github.com/marketplace/actions/upload-a-build-artifact  
      - name: Upload current benchmark artifacts
        uses: actions/upload-artifact@v3
        with:
          name: BenchmarkDotNet.Artifacts.Current
          path: BenchmarkDotNet.Artifacts.Current
      
      # Checkout to main branch
      - name: Checkout to main branch
        uses: actions/checkout@v4
        with:
          ref: main
          clean: false
      
      # Run benchmarks on main branch
      - name: Run Benchmarks on Main
        run: dotnet run -c Release --project ContactBook.Benchmark --filter ContactBook.Benchmark.Features* --artifacts BenchmarkDotNet.Artifacts.Main
        
      # Upload the Results: https://github.com/marketplace/actions/upload-a-build-artifact  
      - name: Upload main benchmark artifacts
        uses: actions/upload-artifact@v3
        with:
          name: BenchmarkDotNet.Artifacts.Main
          path: BenchmarkDotNet.Artifacts.Main

      # Compare the benchmarks
      - name: Compare Benchmarks
        run: dotnet run -c Release --project ContactBook.BenchmarkResultsComparer --base BenchmarkDotNet.Artifacts.Main --diff BenchmarkDotNet.Artifacts.Current --threshold 10%
